#!/bin/bash

COMMAND="sqlite3 db.sqlite3 'delete from welcome_pageview;'"
echo "Running:"
echo "  $COMMAND"

RESULT=$(sqlite3 db.sqlite3 'delete from welcome_pageview;')
echo -e "Result:"
echo "  $RESULT"

